//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarritoEstado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarritoEstado()
        {
            this.CarritoDetalle = new HashSet<CarritoDetalle>();
        }
    
        public int idCarritoEstado { get; set; }
        public string nombreCarritoEstado { get; set; }
        public bool vigente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarritoDetalle> CarritoDetalle { get; set; }
    }
}
