//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarritoDetalle
    {
        public int idCarritoDetalle { get; set; }
        public int idCarrito { get; set; }
        public int idProducto { get; set; }
        public int cantidad { get; set; }
        public int idCarritoEstado { get; set; }
    
        public virtual Carrito Carrito { get; set; }
        public virtual CarritoEstado CarritoEstado { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
