//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.CarritoDetalle = new HashSet<CarritoDetalle>();
        }
    
        public int idProducto { get; set; }
        public int idCategoria { get; set; }
        public string nombreProducto { get; set; }
        public int precio { get; set; }
        public string descripcion { get; set; }
        public byte[] imagen { get; set; }
        public bool isOferta { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public bool vigente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarritoDetalle> CarritoDetalle { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
